[tool.uv.workspace]
members = ["modules/agent_tools", "modules/hub", "modules/workflow"]

[tool.rye.workspace]
members = ["modules/agent_tools", "modules/hub", "modules/workflow"]

[tool.ruff]
exclude = [".git", ".venv", "migrations"]
line-length = 120
target-version = "py313"

[tool.ruff.lint]
select = ["E", "F", "I", "B"]
ignore = ["E501"]

[tool.ruff.lint.per-file-ignores]
"**/tests/**/*.py" = ["F403", "E402"]
"__init__.py" = ["F403"]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"

[tool.pyright]
venvPath = "."
venv = ".venv"
pythonVersion = "3.13"
typeCheckingMode = "basic"
extraPaths = ["./modules/agent_tools", "./modules/hub", "./modules/workflow"]
